name:                x
version:             0.0.4.0
github:              "jonathan-lemos/x"
license:             "Apache-2.0"
author:              "Jonathan Lemos"
maintainer:          "jonathanlemos@protonmail.com"
copyright:           "2022 Jonathan Lemos"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/jonathan-lemos/x#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal
- containers
- numbers
- terminal-size
- validation

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -Werror
    - -Wno-unused-do-bind
    - -Wno-name-shadowing

executables:
  x-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wno-unused-do-bind
    - -Wno-name-shadowing
    dependencies:
    - x

tests:
  x-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - x
    - hspec
    - QuickCheck
    - split
