name: ci
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    name: Builds and tests

    runs-on: ubuntu-latest

    strategy:
      matrix:
        stack: ["2.7.5"]
        cabal: ["3.6.2.0"]
        ghc: ["8.10.7"]

    steps:
    - uses: actions/checkout@v3
      name: Checkout code

    - uses: haskell/actions/setup@v2
      name: Setup GHC and Stack
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}

    - name: Add Cabal bin to $PATH
      run: echo "${HOME}/.cabal/bin" >> $GITHUB_PATH

    - uses: actions/cache@v3
      name: Cache Cabal and Stack work directories
      with:
        path: |
          ~/.stack
          .stack-work
          ~/.cabal
        key: ${{ matrix.ghc }}-${{ matrix.cabal }}-${{ matrix.stack }}

    - name: Update Cabal mirrors
      run: cabal update

    - uses: haskell/actions/hlint-setup@v2
      name: Setup hLint
      with:
        version: "3.3.6"

    - name: Build
      run: stack build

    - uses: haskell/actions/hlint-run@v2
      name: Run hLint
      with:
        path: src/
        fail-on: warning

    - name: Run hSpec tests
      run: stack test
